export const data = [
  //   {
  //     id: 101,
  //     title: "Item1",
  //     author: "Mahesh",
  //     ingredients: "garlic,ginger",
  //   },
  {
    id: 1,
    title: "Hummus",
    author: "Chef Ali",
    ingredients: [
      "2 cups chickpeas (cooked or canned)",
      "1/4 cup fresh lemon juice",
      "1/4 cup tahini",
      "1 small garlic clove, minced",
      "2 tablespoons olive oil",
      "1/2 teaspoon ground cumin",
      "Salt to taste",
      "2-3 tablespoons water",
      "Dash of paprika (optional, for garnish)",
      "Fresh parsley (optional, for garnish)",
    ],
    steps: [
      "Combine tahini and lemon juice in a food processor and blend for 1 minute.",
      "Add the olive oil, minced garlic, cumin, and salt to the tahini mixture and blend for another 30 seconds.",
      "Add half of the chickpeas to the food processor and blend for 1 minute.",
      "Add the remaining chickpeas and blend until smooth, about 1-2 minutes.",
      "If the hummus is too thick, add 1-2 tablespoons of water until the desired consistency is reached.",
      "Transfer the hummus to a serving bowl and garnish with paprika and fresh parsley if desired.",
    ],
    image_url: "hummus.jpeg",
  },
  {
    id: 2,
    title: "Falafel",
    author: "Chef Fatima",
    ingredients: [
      "1 cup dried chickpeas (soaked overnight)",
      "1/2 large onion, roughly chopped",
      "2 tablespoons fresh parsley, chopped",
      "2 tablespoons fresh cilantro, chopped",
      "1 teaspoon salt",
      "1 teaspoon ground cumin",
      "1 teaspoon ground coriander",
      "1/2 teaspoon black pepper",
      "1/4 teaspoon cayenne pepper",
      "1/4 teaspoon ground cardamom",
      "1 teaspoon baking powder",
      "1/2 teaspoon baking soda",
      "Vegetable oil for frying",
    ],
    steps: [
      "Drain the soaked chickpeas and transfer them to a food processor.",
      "Add the onion, parsley, cilantro, salt, cumin, coriander, black pepper, cayenne pepper, and cardamom to the food processor.",
      "Process the mixture until it is finely ground, but not pureed.",
      "Add the baking powder and baking soda to the mixture and pulse a few times to combine.",
      "Transfer the mixture to a bowl, cover, and refrigerate for at least 1 hour.",
      "Form the mixture into small balls or patties using your hands or a falafel scoop.",
      "Heat vegetable oil in a deep pan over medium heat.",
      "Fry the falafel in batches until golden brown and crispy, about 3-4 minutes per side.",
      "Drain the falafel on paper towels and serve hot.",
    ],
    image_url: "Homemade-Falafel-00.jpg",
  },
  {
    id: 3,
    title: "Tabbouleh",
    author: "Chef Layla",
    ingredients: [
      "1 cup bulgur wheat",
      "1 1/2 cups boiling water",
      "1 cup finely chopped fresh parsley",
      "1/2 cup finely chopped fresh mint",
      "1/2 cup finely chopped green onions",
      "2 medium tomatoes, finely diced",
      "1/4 cup fresh lemon juice",
      "1/4 cup extra-virgin olive oil",
      "Salt and pepper to taste",
    ],
    steps: [
      "Place the bulgur wheat in a large bowl and pour the boiling water over it.",
      "Cover the bowl and let the bulgur soak for 20-30 minutes, or until the water is absorbed.",
      "Fluff the bulgur with a fork and let it cool to room temperature.",
      "Add the parsley, mint, green onions, and tomatoes to the bulgur and mix well.",
      "In a small bowl, whisk together the lemon juice, olive oil, salt, and pepper.",
      "Pour the dressing over the tabbouleh and toss to combine.",
      "Refrigerate for at least 1 hour before serving to allow the flavors to meld.",
    ],
    image_url: "istockphoto-1445993034-612x612.jpg",
  },
];
